/**:
  ros__parameters:
    can_interface_type: "SocketCAN"
    can_device_name: "can0"
    
    motors:
      FL_node_id: 1
      FR_node_id: 2
      RL_node_id: 3
      RR_node_id: 4

    motor_parameters:
      acceleration: 1000
      deceleration: 1000
      max_torque: 1000
      end_velocity: 0
      quick_stop_deceleration: 1000
      velocity_window: 15
      velocity_threshold: 15
    
    wheel_parameters:
      wheel_radius: 0.115  # m
      wheel_distance_x: 0.8  # m
      wheel_distance_y: 0.50  # m
    
    control_parameters:
      control_frequency: 50.0  # Hz
      max_linear_velocity_x: 1.0  # m/s
      max_linear_velocity_y: 1.0  # m/s
      max_angular_velocity: 1.5  # rad/s

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    odom_topic_name: "odom"
    
    safety_parameters:
      timeout_ms: 500
      emergency_stop_enabled: true