name: ROS 2 CI (colcon)

on:
  pull_request:           # PR イベント
    branches: [ main ]
  workflow_dispatch: {} 

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ros_distro: [ humble ]   # 必要なら iron / jazzy など追加

    container:
      image: ros:${{ matrix.ros_distro }}-ros-base-jammy   # Ubuntu 22.04 + ROS2

    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}

    steps:
      # 1. ソース取得
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src/motion-control-mecanum
          
      - name: Cache APT packages
        uses: actions/cache@v4             # ★ 前回削除したものを復活
        with:
          path: /var/cache/apt/archives    # DEB を保存して再利用
          key:  apt-${{ runner.os }}-${{ matrix.ros_distro }}-${{ hashFiles('**/package.xml') }}
          restore-keys: |
            apt-${{ runner.os }}-${{ matrix.ros_distro }}-
            
      # 2. ROS ツール類（rosdep, colcon など）
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}

      # 3. 依存パッケージをインストール
      - name: rosdep install
        shell: bash
        run: |
          rosdep update -y
          rosdep install --from-paths ros2_ws --ignore-src -r -y --rosdistro $ROS_DISTRO

      # 4. ビルド
      - name: colcon build
        shell: bash
        working-directory: ros2_ws
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          colcon build --event-handlers console_direct+

      # 5. テスト
      - name: colcon test
        shell: bash
        working-directory: ros2_ws
        run: |
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
